import { ReactElement } from 'react';
import './index.less';
type CheckDrawerTableType = {
    title: string;
    width?: number;
    onClose: Function;
    open: boolean;
    historyStateFooter?: boolean;
    drawerTableLayoutTitle: ReactElement;
    historyTitle?: string;
    historyDrawerTableLayoutTitle?: ReactElement;
    footerValue?: ReactElement;
    isShowInput: boolean;
    onSearch2?: (data: any) => void | boolean;
    onSearch1?: (data: any) => void | boolean;
    initTotal: Number;
    selectedTotal: Number;
    initColumns: any;
    initRequestTable: any;
    selectedColumns: any;
    selectedRequestTable: any;
    initOptions?: any;
    selectOptions?: any;
    initPlaceholder?: string;
    selectedPlaceholder?: string;
    drawerTableLayoutRef1?: any;
    drawerTableLayoutRef2?: any;
};
declare const CheckDrawerTableType: (props: CheckDrawerTableType) => JSX.Element;
export default CheckDrawerTableType;
